apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 1  # Nombre de copies de conteneur
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: mon-portfolio:latest 
        imagePullPolicy: Never  
        ports:
        - containerPort: 80
      
  